### ISSUE TITLE
nw-gyp rebuild error

### ISSUE THREAD

**Issue by metasanjaya** [tojocky/node-printer#83] opened 2015-09-14 12:10 UTC
Z:\sda3\htdocs\koperasi\client\simko-windows\node_modules\printer>nw-gyp rebuild

gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.12.7 | win32 | ia32
gyp http GET http://node-webkit.s3.amazonaws.com/v0.12.7/nw-headers-v0.12.7.tar.
gz
gyp http 404 http://node-webkit.s3.amazonaws.com/v0.12.7/nw-headers-v0.12.7.tar.
gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (C:\Documents and Settings\Administrat
or\Application Data\npm\node_modules\nw-gyp\lib\install.js:234:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (C:\Documents and Settings\Admin
istrator\Application Data\npm\node_modules\nw-gyp\node_modules\request\request.j
s:1008:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)

gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23
)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\\Documents and Settings\\Administrator\\Application
Data\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild"
gyp ERR! cwd Z:\sda3\htdocs\koperasi\client\simko-windows\node_modules\printer
gyp ERR! node -v v0.12.7
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok

**Comment by tojocky** [comment] 2015-09-29 05:11
let me know if you have the same issue with the latest version, 0.2.0

**Comment by tojocky** [comment] 2015-09-29 05:28
dupe of #76

**Closed by tojocky** 2015-09-29 05:28 UTC
Labels: duplicate

**Comment by metasanjaya** [comment] 2015-09-29 05:33
I think because http://node-webkit.s3.amazonaws.com/v0.12.7/nw-headers-v0.12.7.tar.gz was not found (404) so the installer error, how to repair this?

**Comment by tojocky** [comment] 2015-09-29 05:53
specify nwjs version in build

**Comment by metasanjaya** [comment] 2015-09-29 08:07
how to do that please?

**Comment by Phoscur** [comment] 2016-01-17 15:48
nw-gyp rebuild --target=x.x.x
