### ISSUE TITLE
Print not working on Windows (Image Printing)

### ISSUE THREAD

**Issue by Canser** [tojocky/node-printer#154] opened 2016-12-01 07:49 UTC
Hello.

When i try to print an image document, the module sends the job to the queue, so i can see the printing job, but nothing happens after that, just waiting...

I saw a post similar to my problem, tried to print text with type: text option, printer got the job but printed blank page...

Any idea?

Thank you.

(Edit: It's not blank, text printed but most of it out of borders)

**Comment by happilymarrieddad** [comment] 2017-04-07 16:07
I am experiencing the same problem

++

**Comment by tojocky** [comment] 2017-06-13 04:44
Duplicate of https://github.com/tojocky/node-printer/issues/20

**Closed by tojocky** 2017-06-13 04:44 UTC
