### ISSUE TITLE
Convert Blob data to Raw buffer in javascript or node

### ISSUE THREAD

**Issue by kamaldeepoodles** [tojocky/node-printer#101] opened 2015-12-08 14:33 UTC
I am using a plugin jsPDF (https://github.com/MrRio/jsPDF) which generates PDF and saves it to local file system. Now in jsPDF.js, there is some piece of code which generates pdf data in blob format as:-

var blob = new Blob([array], {type: "application/pdf"});

and further saves the blob data to local file system. Now instead of saving I need to print the PDF using plugin node-printer.

Here is some sample code to do so

var fs = require('fs'),
var dataToPrinter;

fs.readFile('/home/ubuntu/test.pdf', function(err, data){
    dataToPrinter = data;
}

var printer = require("../lib");
printer.printDirect({
    data: dataToPrinter,
    printer:'Deskjet_3540',
    type: 'PDF',
    success: function(id) {
        console.log('printed with id ' + id);
    },
    error: function(err) {
        console.error('error on printing: ' + err);
    }
})
The fs.readFile() reads the PDF file and generates data in raw buffer format.

Now what I want is to convert the 'Blob' data into 'raw buffer' so that I can print the PDF.

**Comment by tojocky** [comment] 2015-12-08 17:08
use:
```javascript
var curBuffer = new Buffer( blob, 'binary' );
...
```

**Comment by kamaldeepoodles** [comment] 2015-12-09 05:02
Today after reaching back to my work place I tested the solution with my printer but the curBuffer data which I provide to printer is putting the printing job on hold. Please look into this what else I could try out

**Comment by tojocky** [comment] 2015-12-09 06:15
First, previous code to make it work you have to move the print command into fs.readFile() closure because fs.readFile is async.

Did you compare the data of saved file and the converted buffer?

**Comment by kamaldeepoodles** [comment] 2015-12-09 06:52
actually I am not using fs.readFile as I directly wanna provide the blob data to printer in suitable format. 

First I generated the PDF using plugin jsPDF (https://github.com/MrRio/jsPDF). In the plugin, there is a file jsPDF.js in which final PDF output is prepared in blob format and then saved to local machine. now what I have is the blob data which I want to pass it to printer.

**Comment by kamaldeepoodles** [comment] 2015-12-09 11:43
Please let me know

**Comment by tojocky** [comment] 2015-12-09 17:07
I think you need to find a proper response on the internet. e.g.: http://stackoverflow.com/questions/15341912/how-to-go-from-blob-to-arraybuffer

The conversion of the blob object into Buffer is not the issue on node-printer.
I'm closing this issue.
Feel free to reopen or open a new one if you think the issue is with node-printer.

**Closed by tojocky** 2015-12-09 17:07 UTC

**Comment by kamaldeepoodles** [comment] 2015-12-10 06:03
var blob = new Blob([array], {type: "application/pdf"});
                        
                    var arrayBuffer, uint8Array;
                    var fileReader = new FileReader();
                    fileReader.onload = function() {
                        arrayBuffer = this.result;
                        uint8Array  = new Uint8Array(arrayBuffer);
                        
                        var printer = require("./js/controller/lib");
                        printer.printDirect({
                            data: uint8Array,
                            printer:'Deskjet_3540',
                            type: 'PDF',
                            success: function(id) {
                                console.log('printed with id ' + id);
                            },
                            error: function(err) {
                                console.error('error on printing: ' + err);
                            }
                        })
                    };
                    fileReader.readAsArrayBuffer(blob);


This is the final code which worked for me. The printer accepts uint8Array encoding format.

**Comment by tojocky** [comment] 2015-12-10 06:44
Buffer now is the same as ArrayBuffer, early versions of node (<=0.12) it was a simple C++ memory allocation. This may not work with early version of node.

**Comment by kamaldeepoodles** [comment] 2015-12-10 07:06
My Node version is 0.12.7 and node webkit version is 0.12.3

Ok according to you what would work with early versions of node ?

Because var curBuffer = new Buffer( blob, 'binary' ); didn't worked for me

**Comment by tojocky** [comment] 2015-12-10 07:15
the above code did it work for you with node version 0.12.7?
I'm surprised.

the code should look something like:
```javascript
function toBuffer(ab) {
    var buffer = new Buffer(ab.byteLength);
    var view = new Uint8Array(ab);
    for (var i = 0; i < buffer.length; ++i) {
        buffer[i] = view[i];
    }
    return buffer;
}
```

**Comment by kamaldeepoodles** [comment] 2015-12-10 07:44
No this thing isn't working for me.

**Comment by ryhill** [comment] 2019-04-26 06:47
@Kamaldeep's  code worked for me
