### ISSUE TITLE
Nothing gets printed

### ISSUE THREAD

**Issue by ramkishore380** [tojocky/node-printer#38] opened 2015-01-17 14:01 UTC
Hi When i try to print a raw data am getting the script does not show any error, and the print queue shows the print job. But nothing gets printed.

Code
---------

var printer = require("printer");
var printerName = "HP LaserJet P1007" ;

console.log("---------------------")
console.log(printer.getSupportedPrintFormats(printerName))
console.log("---------------------")
console.log(printer.getSupportedJobCommands(printerName))
console.log("---------------------")
printer.printDirect({
data:new Buffer("I will be written"),
printer: printerName,
type: "RAW" , 
success:function(jobID){ 
console.log("Job sent with ID: " + jobID) 
var jobInfo = printer.getJob(printerName, jobID)
console.log("Job info:" + JSON.stringify(jobInfo, null, 2))
},
error:function(err){console.log(err)}
})

Console output
D:\ProjectITCS\bin>node printer.js
---------------------
[ 'RAW', 'TEXT' ]
---------------------
[ 'CANCEL',
  'DELETE',
  'LAST-PAGE-EJECTED',
  'PAUSE',
  'RESTART',
  'RESUME',
  'SENT-TO-PRINTER' ]
---------------------
Job sent with ID: 18
Job info:{
  "id": 18,
  "name": "HP LaserJet P1007",
  "printerName": "HP LaserJet P1007",
  "user": "ram",
  "format": "RAW",
  "priority": 1,
  "size": 17,
  "status": [
    "PRINTING"
  ],
  "machineName": "\\\\RAMKISHORE",
  "document": "node print job",
  "notifyName": "ram",
  "printProcessor": "HP1006PrintProc",
  "driverName": "HP LaserJet P1007",
  "position": 1,
  "startTime": 0,
  "untilTime": 0,
  "totalPages": 1,
  "time": 221645312,
  "pagesPrinted": 0
}

**Comment by tojocky** [comment] 2015-01-17 22:28
Use `type: "TEXT"` instead of `type: "RAW"`

**Comment by ramkishore380** [comment] 2015-01-19 13:16
I tried with "TEXT" instead of "RAW". But i am getting the error [TypeError: StartDocPrinter error].

**Comment by tojocky** [comment] 2015-01-19 20:56
This is a different error. Either you change node/node-webkit version, either you set wrong printer name.

**Comment by ramkishore380** [comment] 2015-01-23 04:51
I tried passing the printer name from the output of GetPrinters function. Still i get the same error.
Am using windows 8 and latest version of node JS 0.10.35. Please suggest me which version to use

**Comment by niaochaobao** [comment] 2015-01-23 06:56
I met the same same error like ramkishore380. the print queue shows the print job. But nothing gets printed.

**Comment by tojocky** [comment] 2015-01-23 08:45
@ramkishore380 Could you please try latest dev version: 0.11.14?
@niaochaobao did you try also to print with `type:"TEXT"`?

**Comment by ramkishore380** [comment] 2015-02-01 15:14
Hi,

Am still getting the error even with version 0.11.14.

Regards,
R.Ram Kishore

**Comment by tojocky** [comment] 2015-02-01 18:09
could you please publish your code? at least a simplified code.

**Comment by ramkishore380** [comment] 2015-02-02 04:26
var printer = require("printer");
var printerName = "HP LaserJet P1007" ;

console.log("---------------------")
console.log(printer.getSupportedPrintFormats(printerName))
console.log("---------------------")
console.log(printer.getSupportedJobCommands(printerName))
console.log("---------------------")
printer.printDirect({
data:new Buffer("I will be written"),
printer: printerName,
type: "TEXT" , 
success:function(jobID){ 
console.log("Job sent with ID: " + jobID) 
var jobInfo = printer.getJob(printerName, jobID)
console.log("Job info:" + JSON.stringify(jobInfo, null, 2))
},
error:function(err){console.log(err)}
})

**Comment by tojocky** [comment] 2015-02-02 05:33
I suspect your printer does not support utf8.
Could you please try to send data direct into text?
`data:"I will be written"`

**Comment by tojocky** [comment] 2015-02-02 05:44
Or `data:new Buffer("I will be written","ascii")`

**Comment by ramkishore380** [comment] 2015-02-03 17:04
I tried providing data in both the ways. Still no luck

**Comment by tojocky** [comment] 2015-02-03 19:21
What is your output? No error?

**Comment by ramkishore380** [comment] 2015-02-04 02:10
getting the same error [TypeError: StartDocPrinter error].

**Comment by ramkishore380** [comment] 2015-02-05 11:21
Any update on this ?

**Comment by tojocky** [comment] 2015-02-05 20:02
in your case fails at StartDocPrinterW, the printer opens OK.
Unfortunately, I didn't find a way to extract the error status.
Could you please try to add `docname`:
```
console.log("---------------------")
console.log(printer.getSupportedPrintFormats(printerName))
console.log("---------------------")
console.log(printer.getSupportedJobCommands(printerName))
console.log("---------------------")
printer.printDirect({
data:"I will be written",
printer: printerName,
type: "TEXT" ,
docname: "Doc1",
success:function(jobID){ 
  console.log("Job sent with ID: " + jobID) 
  var jobInfo = printer.getJob(printerName, jobID)
  console.log("Job info:" + JSON.stringify(jobInfo, null, 2))
},
error:function(err){console.log(err)}
})
```

**Comment by ramkishore380** [comment] 2015-02-07 13:07
I tried adding the DocName and still it din work. 

Am able to print using other applications like MSword, adobe arobat etc.

My OS is windows 8 and 64 bit arch

The output for getPrinter(printerName) is
---------------------
{ name: '?????4??7et P1007',
  portName: '???',
  driverName: '?????4??7et P1007',
  printProcessor: '???????cintProc',
  datatype: '?FF',
  status: [],
  statusNumber: 0,
  attributes: [ 'DO-COMPLETE-FIRST', 'LOCAL' ],
  priority: 1,
  defaultPriority: 0,
  averagePPM: 0 }

i could see some of the values are corrupted.

**Comment by tojocky** [comment] 2015-02-07 16:45
Indeed, this may explain why you couldn't print.

**Comment by tojocky** [comment] 2015-02-07 17:23
What nide.js version did you use?

**Comment by ramkishore380** [comment] 2015-02-07 20:34
Yes, i understand. But the printer name i use is the one that i get from the getPrinters() function. I use tried with nodejs version 0.10.35 and 0.11.14. No luck in both the cases. 

Could you please suggest me what would resolve this issue ? Am i doing anything wrong in the code? 

Also can u suggest me which OS and printers is the module working fine ?

**Comment by tojocky** [comment] 2015-02-07 21:07
I tested on windows 8 pro 64bit, macos 10.7 and archlinux. will investigate and will get with a solution.
I suspect the issue is with UTF8.

**Comment by tojocky** [comment] 2015-02-08 16:44
I don't have any windows OS noe.
Could you please retest getPrinter?

```
var printer = require("printer");
var printerName = "HP LaserJet P1007" ;

console.log("---------------------")
console.log(printer. getPrinter(printerName))
```

At least we have 2 issues:
* getPrinter unicode issue
* print encode issue

**Comment by ramkishore380** [comment] 2015-02-09 01:13
should i reinstall the module and try ?

**Comment by tojocky** [comment] 2015-02-09 07:43
Yes please, from git repository because I did some changes.

**Comment by ramkishore380** [comment] 2015-02-09 13:49
Hi,

now the getPrinter returns the output properly 

{ name: 'HP LaserJet P1007',
  portName: 'USB001',
  driverName: 'HP LaserJet P1007',
  printProcessor: 'HP1006PrintProc',
  datatype: 'IMF',
  status: [],
  statusNumber: 0,
  attributes: [ 'DO-COMPLETE-FIRST', 'LOCAL' ],
  priority: 1,
  defaultPriority: 0,
  averagePPM: 0 }

But still am getting the [TypeError: StartDocPrinter error]. while am doing printDirect. Tried all the suggestions u mentioned earlier. No luck

**Comment by tojocky** [comment] 2015-02-09 15:00
at least 1 issue less.
Seems I found a way to get error code, and hopefully error message string:
* [DWORD WINAPI GetLastError(void)](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162752%28v=vs.85%29.aspx) - return 
* (DWORD WINAPI FormatMessage())[https://msdn.microsoft.com/en-us/library/windows/desktop/ms679351%28v=vs.85%29.aspx]

A possible solution is to use (BOOL OpenPrinter2W())[https://msdn.microsoft.com/en-us/library/windows/desktop/dd162752%28v=vs.85%29.aspx] instead of (BOOL OpenPrinterW())[https://msdn.microsoft.com/en-us/library/windows/desktop/dd162751%28v=vs.85%29.aspx] for are more complex open printer.

I will add first error detail but you will test this on your device. This will hhelp to understand what is going wrong.

Could you please describe what OS language do you have, also, what is OS language?

**Comment by ramkishore380** [comment] 2015-02-09 15:06
I am unable to get ur question ? OS language in the sense ?

**Comment by tojocky** [comment] 2015-02-09 20:41
Could you please retest the latest version? Reinstall it from git and re-test.
I expect this version to return a more detailed error, to understand what is wrong.

Please note that I didn't even compile, because I don't have any windows OS ( :-( my windows motherboard was burned).

In previous message I meant what is [display language](http://windows.microsoft.com/en-gb/windows7/install-or-change-a-display-language) of your windows OS.

**Comment by ramkishore380** [comment] 2015-02-10 00:11
D:\ProjectITCS\bin>node printer.js
---------------------
[ 'RAW', 'TEXT' ]
---------------------
[ 'CANCEL',
  'DELETE',
  'LAST-PAGE-EJECTED',
  'PAUSE',
  'RESTART',
  'RESUME',
  'SENT-TO-PRINTER' ]
---------------------
[TypeError: StartDocPrinterW error: code: 1804, message: The specified datatype
is invalid.
]

**Comment by tojocky** [comment] 2015-02-10 05:31
Seems TEXT data type is not supported by your printer. Strange.

**Comment by ramkishore380** [comment] 2015-02-10 05:36
https://social.msdn.microsoft.com/Forums/vstudio/en-US/012942ff-1ffd-4758-bb1b-d3c1db0dcb46/startdocprinter-fails-could-not-start-print-job?forum=windowsgeneraldevelopmentissues

I did get this info from the above link as well. What do you suggest can be done ?

**Comment by tojocky** [comment] 2015-02-10 05:41
http://www.papercut.com/kb/Main/TheSpecifiedDatatypeIsInvalid

**Comment by ramkishore380** [comment] 2015-02-10 05:42
Ok let me check that and let u know if that works

**Comment by tojocky** [comment] 2015-02-10 05:46
From previous message, getPrinter, I see that it supports only IMF. This may explain why.

Could you please try to uninstall AMD reinstall with latest printer drivers version?

**Comment by ramkishore380** [comment] 2015-02-10 14:21
I did a small configuration change in the printer properties and now the startdocprinter error does not occur

![image](https://cloud.githubusercontent.com/assets/10542162/6128679/f3394db8-b15d-11e4-88f9-1ebe0d36f0f7.png)

But now, the print job is shown in the printer queue and my printer makes usual sounds, and then nothing gets printed. if you could see the screenshot it shows the status to be printing

**Comment by ramkishore380** [comment] 2015-02-10 14:23
D:\ProjectITCS\bin>node printer.js
---------------------
[ 'RAW', 'TEXT' ]
---------------------
[ 'CANCEL',
  'DELETE',
  'LAST-PAGE-EJECTED',
  'PAUSE',
  'RESTART',
  'RESUME',
  'SENT-TO-PRINTER' ]
---------------------
Job sent with ID: 13
Job info:{
  "id": 13,
  "name": "HP LaserJet P1007",
  "printerName": "HP LaserJet P1007",
  "user": "ramki",
  "format": "TEXT",
  "priority": 1,
  "size": 17,
  "status": [],
  "machineName": "\\\\RAMKISHORE",
  "document": "Doc1",
  "notifyName": "ramki",
  "printProcessor": "winprint",
  "driverName": "HP LaserJet P1007",
  "position": 1,
  "startTime": 0,
  "untilTime": 0,
  "totalPages": 1,
  "time": 0,
  "pagesPrinted": 0
}

**Comment by tojocky** [comment] 2015-02-10 20:45
This seems to be a print processor issue.
Could you please try to send in ASCII charset data by using buffer?
```
var printer = require("printer");
var printerName = "HP LaserJet P1007" ;

console.log("---------------------")
console.log(printer.getSupportedPrintFormats(printerName))
console.log("---------------------")
console.log(printer.getSupportedJobCommands(printerName))
console.log("---------------------")
printer.printDirect({
data:new Buffer("I will be written", "ascii"), // here is buffer
printer: printerName,
type: "TEXT" ,
docname: "Doc1",
success:function(jobID){ 
  console.log("Job sent with ID: " + jobID) 
  var jobInfo = printer.getJob(printerName, jobID)
  console.log("Job info:" + JSON.stringify(jobInfo, null, 2))
},
error:function(err){console.log(err)}
})
```

**Comment by ramkishore380** [comment] 2015-02-11 13:39
Tried with ASCII, same result. Not printing :-(

**Comment by tojocky** [comment] 2015-02-12 10:32
the issue seems to be on TEXT processor side. I don't have any idea could fix this

**Comment by ramkishore380** [comment] 2015-02-12 10:33
Is it possible to execute the same thru RAW data format ?

**Comment by tojocky** [comment] 2015-02-12 10:43
try... but once you set RAW type, you tell to printer that data contain binary commands. You have to send commands what your printer to understand .

**Comment by ramkishore380** [comment] 2015-02-12 10:44
OK thank you.  I will dig into it. If am successful will update u :-)
thanks a lot

**Comment by tojocky** [comment] 2015-02-25 21:06
I'm closing this issue.

**Closed by tojocky** 2015-02-25 21:06 UTC
Labels: bug

**Comment by jasminmif** [comment] 2016-05-17 21:14
@ramkishore380  Hey did you find a way to get the Printing Queue i get the same error i have the same Printer Model just with wifi: HP LaserJet Professional P 1102w_1

**Comment by igorcandeia** [comment] 2016-11-17 20:18
I get the same error,
 `TypeError: StartDocPrinterW error: code: 1804`

**Comment by guidopontet** [comment] 2019-09-17 20:07
Same on HP LaserJet Professional P 1102w.

```
StartDocPrinterW error: code: 1804, message: not valid data type
```

Available types are: `RAW` and `IMF`. `TEXT` is not present.
