### ISSUE TITLE
Image Printing in Windows

### ISSUE THREAD

**Issue by alexmccabe** [tojocky/node-printer#168] opened 2017-03-30 09:26 UTC
I am trying to print an image in Windows (IA32). The application can find and print to the printer, however it prints out the raw image data and a tonne of blank pages.

    let filePath = path.join(process.resourcesPath, '/app', file);

    if (process.platform !== 'win32') {
        Printer.printFile({
            filename: filePath,
            printer: self.getCurrentPrinter(),
             success: function (jobID) {
                 console.log('success', jobID);
             },
             error: function (error) {
                 console.log(error);
             }
            });
     } else {
         Printer.printDirect({
             filename: fs.readFileSync(filePath),
             printer: self.getCurrentPrinter(),
             success: function (jobID) {
                 console.log('success', jobID);
             },
             error: function (error) {
                 console.log(error);
             }
         });
     }

Am I missing something in the configuration for `win32` platforms? Everything works as expected on OSX.

**Comment by Cyanodioxine** [comment] 2017-06-10 21:23
I too am unable to print images (or anything, for that matter).
However, in the Windows implementation, you need to have this for your configuration:
`data: fs.readFileSync(filePath)`
printDirect requires data, not filename.

**Comment by tojocky** [comment] 2017-06-13 04:44
Duplicate of https://github.com/tojocky/node-printer/issues/20

**Closed by tojocky** 2017-06-13 04:44 UTC

**Comment by prasheel888** [comment] 2022-04-25 09:04
> I am trying to print an image in Windows (IA32). The application can find and print to the printer, however it prints out the raw image data and a tonne of blank pages.
> 
> ```
> let filePath = path.join(process.resourcesPath, '/app', file);
> 
> if (process.platform !== 'win32') {
>     Printer.printFile({
>         filename: filePath,
>         printer: self.getCurrentPrinter(),
>          success: function (jobID) {
>              console.log('success', jobID);
>          },
>          error: function (error) {
>              console.log(error);
>          }
>         });
>  } else {
>      Printer.printDirect({
>          filename: fs.readFileSync(filePath),
>          printer: self.getCurrentPrinter(),
>          success: function (jobID) {
>              console.log('success', jobID);
>          },
>          error: function (error) {
>              console.log(error);
>          }
>      });
>  }
> ```
> 
> Am I missing something in the configuration for `win32` platforms? Everything works as expected on OSX.

Bro how did you get this done? facing a same issue

**Comment by alexmccabe** [comment] 2022-04-25 10:26
Oh god this was so long ago, I'm like four jobs along. I didn't, we ended up using a Mac Mini in the end

**Comment by prasheel888** [comment] 2022-04-25 10:29
> Oh god this was so long ago, I'm like four jobs along. I didn't, we ended up using a Mac Mini in the end

understood, thanks bro1
